// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelKickers.Api.Daten;

#nullable disable

namespace TravelKickers.Api.Migrations
{
    [DbContext(typeof(TkContext))]
    partial class TkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TravelKickers.Api.Daten.Anhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Laenge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VereinId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.ToTable("Anhaenge");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.AnhangDaten", b =>
                {
                    b.Property<int>("AnhangId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("AnhangId");

                    b.ToTable("AnhangDaten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Betreuung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Bis")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TherapeutId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Von")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("TherapeutId", "KlientId")
                        .IsUnique();

                    b.ToTable("Betreuungen");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Einstellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DauerSek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mindesttrefferquote")
                        .HasColumnType("REAL");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpielId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stufe")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Toleranz")
                        .HasColumnType("REAL");

                    b.Property<double>("Zielgeschwindigkeit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KlientId", "SpielId")
                        .IsUnique();

                    b.ToTable("Einstellungen");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Geraet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ZuletztGesehen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Geraete");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PausenDauerSek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PausenInhalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spielname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klienten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Kopplungscode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EingeloestAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Fehlversuche")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LaeuftAbAm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("KlientId");

                    b.ToTable("Kopplungscodes");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Rohdaten", b =>
                {
                    b.Property<Guid>("SpielergebnisId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AbtastrateHz")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anzahl")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Werte")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("SpielergebnisId");

                    b.ToTable("Rohdaten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BeendetAmMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BegonnenAmMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EmpfangenAm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GeraetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VereinId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GeraetId");

                    b.HasIndex("KlientId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.SessionEreignis", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Folgenummer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nutzlast")
                        .HasColumnType("TEXT");

                    b.Property<long>("ZeitMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "Folgenummer");

                    b.ToTable("SessionEreignisse");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Spielergebnis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Abgebrochen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DauerMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DruckMittel")
                        .HasColumnType("REAL");

                    b.Property<double>("DruckStreuung")
                        .HasColumnType("REAL");

                    b.Property<string>("Eingabegeraet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extra")
                        .HasColumnType("TEXT");

                    b.Property<double>("Genauigkeit")
                        .HasColumnType("REAL");

                    b.Property<int?>("Selbsteinschaetzung")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpielId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stufe")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SynthetischerDruck")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Vollstaendigkeit")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Spielergebnisse");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Therapeut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswortHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Therapeuten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Anhang", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany("Anhaenge")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.AnhangDaten", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Anhang", "Anhang")
                        .WithOne("Daten")
                        .HasForeignKey("TravelKickers.Api.Daten.AnhangDaten", "AnhangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anhang");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Betreuung", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany("Betreuungen")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelKickers.Api.Daten.Therapeut", "Therapeut")
                        .WithMany("Betreuungen")
                        .HasForeignKey("TherapeutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");

                    b.Navigation("Therapeut");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Einstellung", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany("Einstellungen")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Geraet", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany("Geraete")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Kopplungscode", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany()
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Rohdaten", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Spielergebnis", "Spielergebnis")
                        .WithOne("Rohdaten")
                        .HasForeignKey("TravelKickers.Api.Daten.Rohdaten", "SpielergebnisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spielergebnis");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Session", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Geraet", "Geraet")
                        .WithMany()
                        .HasForeignKey("GeraetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelKickers.Api.Daten.Klient", "Klient")
                        .WithMany("Sessions")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Geraet");

                    b.Navigation("Klient");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.SessionEreignis", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Session", "Session")
                        .WithMany("Ereignisse")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Spielergebnis", b =>
                {
                    b.HasOne("TravelKickers.Api.Daten.Session", "Session")
                        .WithMany("Ergebnisse")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Anhang", b =>
                {
                    b.Navigation("Daten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Klient", b =>
                {
                    b.Navigation("Anhaenge");

                    b.Navigation("Betreuungen");

                    b.Navigation("Einstellungen");

                    b.Navigation("Geraete");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Session", b =>
                {
                    b.Navigation("Ereignisse");

                    b.Navigation("Ergebnisse");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Spielergebnis", b =>
                {
                    b.Navigation("Rohdaten");
                });

            modelBuilder.Entity("TravelKickers.Api.Daten.Therapeut", b =>
                {
                    b.Navigation("Betreuungen");
                });
#pragma warning restore 612, 618
        }
    }
}
